#!/bin/bash

alias vi="nvim"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Git
alias gb="git branch"
alias grv="git remote -v"
alias gs="git status -sb"
alias gst="git status"
alias gd="git diff"
alias gco="git checkout"
alias gcom="git checkout master"
alias gf="git fetch"
alias gl="git log"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gpgh="git push github master"
alias gpghh="git push github HEAD"
alias gpdo="git push digitalocean master"
alias gpall="gpgh && gpdo"
alias gitclean="git checkout -f --"
alias gitdirty="git reset --hard"

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
else # OS X `ls`
  colorflag="-G"
fi

alias l="ls -l ${colorflag}"
alias la="ls -la ${colorflag}"
alias lsd='ls -l ${colorflag} | grep "^d"'
alias ls="command ls ${colorflag}"
export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'

# Show/hide hidden files in Finder
alias showhddn="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidehddn="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias hidedt="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdt="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

alias countfiles="find . -type f -print | wc -l"

alias rbash='. $HOME/.bash_profile'       # Source the bash profile
alias rzsh='. $HOME/.zshrc'       # Source the bash profile
alias vimrc='$EDITOR $HOME/.vimrc'

# nginx
alias startnginx="sudo /usr/local/nginx/sbin/nginx"
alias stopnginx="sudo /usr/local/nginx/sbin/nginx -s stop"

# tmux
alias tmux="TERM=screen-256color-bce tmux"

# fasd
alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection
