#!/bin/bash

# roots
export DOTFILES_ROOT="$HOME/Projects/dotfiles"
export CONFIG_ROOT="$DOTFILES_ROOT/configurations/shell"

# Setup NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Larger bash history & fine tuning results
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
export HISTIGNORE="-:pwd:exit:date:* --help"

# Prefer US English & use UTF-8
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto"

# CLI colors
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagacad

export DOCKER_HOST=tcp://192.168.99.100:2376
export DOCKER_MACHINE_NAME=default
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH=$HOME/.docker/machine/machines/default

export GOPATH=$HOME/Projects/GoSpace

export PATH=$GOPATH/bin:$PATH
