#!/bin/bash

function setupPath {

  paths_to_add=(
    "/usr/local/go/bin"
    "$HOME/.npm-packages/bin"
    "$HOME/bin"
    "sbin"
    "/usr/sbin"
    "/bin"
    "/usr/bin"
    "/usr/local"
    "/usr/local/bin"
    "$HOME/bin"
    "$HOME/Library/Python/2.7/lib/python"
  )

  for p in ${paths_to_add[@]}
  do
    if [[ ":$PATH:" != *$p* ]]; then
      export PATH=$p:$PATH
    fi
  done
}

setupPath
