#!/bin/bash
# Easier navigation: .., ..., ...., ....., $HOME and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Shortcuts to directories
alias d="cd $HOME/Documents/Dropbox"
alias dl="cd $HOME/Downloads"
alias dt="cd $HOME/Desktop"
alias ws="cd $HOME/ws"

# Convenience helpers for go paths
alias goroot="cd $GOROOT"
alias gort="goroot"
alias gosrc="cd $GOROOT/src"
alias gogit="cd $GOROOT/src/github.com"
alias gorca="cd $GOROOT/src/github.com/realchaseadams"

# Editors
alias v="vim"
alias s="subl ."
alias e="$EDITOR"

# Git
alias g="git"
alias gs="git status"
alias gd="git diff"
alias gl="git log"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gitclean="git checkout -f --"
alias gitdirty="git reset --hard"

# Remapping grep to have colors
alias grep="grep --color=auto"

# Shortcuts to commands
alias ehosts='sudo $EDITOR /etc/hosts'
alias h="history"
alias o="open"
alias oo="open ."
alias cl="clear"

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
else # OS X `ls`
  colorflag="-G"
fi

# List all files colorized in long format
alias l="ls -l ${colorflag}"

# List all files colorized in long format, including dot files
alias la="ls -la ${colorflag}"

# List only directories
alias lsd='ls -l ${colorflag} | grep "^d"'

# Always use color output for `ls`
alias ls="command ls ${colorflag}"
export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'

# Show/hide hidden files in Finder
alias showhddn="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidehddn="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias hidedt="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdt="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Enable/Disable Spotlight
alias spotoff="sudo mdutil -a -i off"
alias spoton="sudo mdutil -a -i on"

alias rbash='. $HOME/.bash_profile'       # Source the bash profile
alias ebash='$EDITOR $HOME/.bash_profile' # Open bash profile with default editor
alias lbash='$EDITOR $HOME/bin/.local'    # Open local profile with default editor

# nginx
alias startnginx="sudo /usr/local/nginx/sbin/nginx"
alias stopnginx="sudo /usr/local/nginx/sbin/nginx -s stop"

