cask "visual-studio-code"
cask "google-chrome"
cask "alfred"
cask "hammerspoon"
cask "spotify"
cask "iterm2"
cask "notion"
cask "docker" 

brew "git"
brew "go"
brew "python3"
brew "zsh"
brew "mtr"
brew "screenfetch"