tap "homebrew/cask-fonts"
tap "supabase/tap"

brew "supabase"

brew "antidote" # zsh plugin manager
brew "caddy"
brew "ccat"
brew "cloudflared"
brew "fzf"
brew "jq"
brew "nvm"
brew "rg"
brew "screenfetch"
brew "tree"
brew "volta"
brew "nvim"
brew "marksman"
brew "zk"
brew "stylua"
brew "python"
brew "pipx"
brew "flyctl"

cask "arc"
cask "cleanshot"
cask "1password"
cask "kitty"
cask "raycast"
cask "around"
cask "discord"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "karabiner-elements"
cask "keybase"
cask "loom"
cask "ngrok"
cask "notion"
cask "postman"
cask "readdle-spark"
cask "rocket" # emoji quick picker
cask "slack"
cask "screenflow"
cask "spotify"
cask "vanilla" # hide mac menu bar
cask "visual-studio-code"
cask "mongodb-compass"
cask "obsidian"
cask "cursor"
