#!/bin/bash
# Add `~/bin` and `/usr/local/bin` to the `$PATH`
export PATH="$HOME/bin:/usr/local/bin:/usr/local:$PATH"

# Make vim the default editor
export EDITOR="vim"

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups

# Make some commands not show up in history
export HISTIGNORE="-:pwd:exit:date:* --help"

# Prefer US English and use UTF-8
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto"

# Link Homebrew casks in `/Applications` rather than `~/Applications`
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# ZOMG Colors!
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagacad

# Necessary for go
export GOROOT=$HOME/go
export PATH=$PATH:$GOROOT/bin

