#!/bin/zsh

#source $HOME/dotfiles/configurations/zsh/git_prompt
#autoload -U colors && colors # Enable colors in prompt

#POWERLEVEL9K_MODE='awesome-patched'

SEG_SEPARATOR="$"
PROMPT="%{$FG[069]%}${SEG_SEPARATOR} %{$reset_color%}"


