#!/bin/zsh

source $HOME/dotfiles/configurations/zsh/git_prompt
autoload -U colors && colors # Enable colors in prompt

POWERLEVEL9K_MODE='awesome-patched'

SEGMENT_SEPARATOR=$'⚒ »'

PROMPT="%{$FG[075]%}%~%  \$(git_prompt_string) %{$reset_color%}node@\$(node -v) npm@\$(npm -v)
%{$FG[201]%} $SEGMENT_SEPARATOR%{$reset_color%} "

