#!/bin/sh

# install developer build tools
sudo zypper install --type pattern devel_basis

sudo zypper install \
  git \
  i3

mkdir -p $HOME/src $HOME/bin $HOME/pkg $HOME/tmp

cd $HOME/tmp && \
  curl https://storage.googleapis.com/golang/go1.7.3.src.tar.gz | tar xvz
  

git clone git@github.com:chaseadamsio/dotfiles.git
