#!/bin/sh

# install developer build tools
sudo zypper install --type pattern devel_basis

sudo zypper install \
  git \
  i3

mkdir -p $HOME/src $HOME/bin $HOME/pkg $HOME/tmp

export GO_VERSION=1.7.3
(curl -sSL "https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz" | sudo tar -v -C /usr/local -xz)
  
git clone git@github.com:chaseadamsio/dotfiles.git $HOME/src/chaseadamsio/dotfiles

cd $HOME/src/chaseadamsio/dotfiles && make dotfiles-bootstrap
