brew install tree
brew install autoconf
brew install automake
brew install cmake
brew install fish
brew install flow
brew install gettext
brew install hub
brew install hugo
brew install libevent
brew install libtool
brew install mercurial
brew install neovim
brew install openssl
brew install pcre
brew install pkg-config
brew install reattach-to-user-namespace
brew install tmux
brew install tomcat7
brew install tree
brew install vim

