#!/bin/bash
# $1 the command to run for all of the files from the loop
# $2 path to look for the files
doAllConfigs() {
  for file in $(find -H "$2" -name '*.syml'); do 
    SYMLINK=$(echo "$(basename $file)" | sed 's/.syml//g'); 

    # if the symlink contains .alias, it will find alias: in the file and 
    # determine where to lnk the file to
    if [[ "$SYMLINK" =~ ".alias" ]]; then 
      SYMLINK=$(cat "$file" | grep -Po "alias: (.*)" | sed 's/alias: //g'); 
      if [[ -d "$SYMLINK" ]]; then
        dir=$(dirname $SYMLINK); 
        mkdir -p $HOME/$dir; 
      fi
    else
      SYMLINK=".$SYMLINK"
    fi

    SYMLINK_PATH="$HOME/$SYMLINK"
    case "$1" in
      ln) sudo ln -sf $file "$SYMLINK_PATH"; 
        echo "generating symlink from $file to $SYMLINK_PATH";
        ;;
      rm) sudo rm "$SYMLINK_PATH";
        echo "removing symlink from $file to $SYMLINK_PATH";
        ;;
    esac
  done
}

doAllConfigs "$1" "$2"
